name: Bot Pubblicazione Immobiliare

on:
  workflow_dispatch:
  schedule:
    - cron: '40 10 * * *' # 10:40 UTC corrisponde alle 11:40 in Italia

jobs:
  esegui-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del codice
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installa le librerie necessarie
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Esegui il bot Python
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          WP_PASSWORD: ${{ secrets.WP_PASSWORD }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          YT2_CLIENT_ID: ${{ secrets.YT2_CLIENT_ID }}
          YT2_CLIENT_SECRET: ${{ secrets.YT2_CLIENT_SECRET }}
          YT2_REFRESH_TOKEN: ${{ secrets.YT2_REFRESH_TOKEN }}
          FB_PAGE_TOKEN: ${{ secrets.FB_PAGE_TOKEN }}
          FB_PAGE_ID: ${{ secrets.FB_PAGE_ID }}
        run: python bot.py
