- name: Esegui il bot Python
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          WP_PASSWORD: ${{ secrets.WP_PASSWORD }}
          # GUARDA QUI SOTTO: la variabile a sinistra ha _JSON, quella a destra no!
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          YT2_CLIENT_ID: ${{ secrets.YT2_CLIENT_ID }}
          YT2_CLIENT_SECRET: ${{ secrets.YT2_CLIENT_SECRET }}
          YT2_REFRESH_TOKEN: ${{ secrets.YT2_REFRESH_TOKEN }}
        run: python bot.py
