name: Bot Statistiche Notturno

# Si attiva in automatico alle 03:00 di notte (ora italiana)
on:
  schedule:
    - cron: '0 2 * * *'
  # Questo pulsante ti permette di avviarlo manualmente quando vuoi per testarlo!
  workflow_dispatch: 

jobs:
  aggiorna_statistiche:
    runs-on: ubuntu-latest

    steps:
    - name: Scarica il codice
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Aggiorna indici e Installa ffmpeg (Necessario per gestire i video)
      run: |
        sudo apt-get update
        sudo apt-get install -y --fix-missing ffmpeg

    - name: Installa le librerie
      run: |
        python -m pip install --upgrade pip
        pip install requests gspread google-api-python-client google-auth google-auth-oauthlib google-auth-httplib2 yt-dlp

    - name: Esegui il Commercialista Notturno 🦉
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        FB_PAGE_TOKEN: ${{ secrets.FB_PAGE_TOKEN }}
        FB_PAGE_ID: ${{ secrets.FB_PAGE_ID }}
        YT2_CLIENT_ID: ${{ secrets.YT2_CLIENT_ID }}
        YT2_CLIENT_SECRET: ${{ secrets.YT2_CLIENT_SECRET }}
        YT2_REFRESH_TOKEN: ${{ secrets.YT2_REFRESH_TOKEN }}
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: python bot_statistiche.py
